version: "3"
services:
  api:
    build: ./api
    ports: 
      - "8000:8000"
    volumes:
      - ./api/src:/api/src
      - ./api/test:/api/test
    depends_on:
      - database
    command: ["npm", "run", "dev"]
  web:
    build: ./web
    ports: 
      - "8001:8001"
    volumes:
      - ./web/src:/web/src
      - ./web/test:/web/test
    command: ["npm", "run", "dev"]
    depends_on:
      - api
  database:
    image: "mongo:latest"
    ports: 
      - "27018:27017"