version: "3"
services:
  api:
    build: ./api
    ports: 
      - "8000:8000"
    volumes:
      - ./api/src:/api/src
      - ./api/test:/api/test
    command: ["npm", "run", "dev"]
  database:
    image: "mongo:latest"